<?php
/**
 * bannermanager slider template
 * @author Xigen
 */
?>
<?php
/*
$block_data = $block->getBlockData();

$blocks     = $block_data['block'];
$banners    = $block_data['banners'];
$slider     = $block_data['block']->getData();

?>
    <?php foreach($banners as $banner) : ?>

        <?php if($banner['banner_youtube']): ?>

            <iframe width="200" height="250" src="https://www.youtube.com/embed/<?php echo $banner['banner_youtube']; ?>" frameborder="0" allowfullscreen></iframe>

        <?php else: ?>

            <div class="banner">
                <?php if(!empty($banner['banner_link'])): ?>
                <a href="<?php echo $banner['banner_link'];?>">
                <?php endif; ?>
                <img class="banner_image" src="<?php echo $this->getBaseUrl() . $banner['banner_image'];?>" alt="<?php echo $banner['banner_title']; ?>" title="<?php echo $banner['banner_title']; ?>" />

                <?php if($banner['banner_show_title'] && !empty($banner['banner_title'])): ?>
                <h3 class="banner_title"><?php echo $banner['banner_title'];?></h3>
                <?php endif; ?>

                <?php if(!empty($banner['banner_caption'])): ?>
                <p class="banner_caption"><?php echo $banner['banner_caption'];?></p>
                <?php endif; ?>

                <?php if(!empty($banner['banner_link'])): ?>
                </a>
                <?php endif; ?>
            </div>

        <?php endif; ?>

    <?php endforeach;*/ ?>
