<?php
/**
 * bannermanager slider template
 * @author Xigen
 */
?>
<div id="homepage-carousel">
    <div class="hero-slider">
        <?php $i = 0; foreach ($block->getBannerCollection() as $banner): $i++; ?>
        <div class="slide <?php echo (($i == 1) ? 'active' : '');?>" data-id="<?php echo $banner->getId(); ?>">
            <?php if($banner->getClickUrl()) : ?><a href="<?php echo $banner->getClickUrl(); ?>" target="<?php echo $banner->getTargetValue() ?>"><?php endif; ?>
            <img src="<?php echo $block->getBannerImageUrl($banner) ?>" title="<?php echo $banner->getName(); ?>" alt="<?php echo $banner->getName(); ?>" class="img-responsive" />
            <div class="carousel-caption">
                <?php if($banner->getShowTitle() && $banner->getName()): ?>
                <h3><?php echo $banner->getName(); ?></h3>
                <?php endif; ?>
                <?php if(!empty($banner->getCaption())): ?>
                <?php echo $banner->getCaption(); ?>
                <?php endif; ?>
            </div>
            <?php if($banner->getClickUrl()) : ?></a><?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
</div>

<script>
require(["jquery", "slick.slider"], function($) {
    $(".hero-slider").slick({
        autoplay: true,
        autoplaySpeed: 5000,
        dots: false,
        arrows: false,
        infinite: true,
        slidesToShow: 1,
        slidesToScroll: 1,
        fade: true,
    });
});
</script>
