<?php
/**
 * Xigen
 */
?>
<?php if ($block->isShowTitle() == 1) :
    ?>
    <div class="xigen-bannermanager-title" style="font: bold 12px/16px Arial, Helvetica, sans-serif;text-transform: uppercase;color: #e26703;">
        <strong><span><?php echo $block->escapeHtml($block->getSlider()->getTitle()); ?></span></strong>
    </div>
<?php endif; ?>
<div class="xigen-bannermanager-static">
    <?php foreach ($block->getBannerCollection() as $banner): ?>
        <div>
            <?php if($banner->getClickUrl()): ?>
            <a href="<?php echo $banner->getClickUrl() ?>" target="<?php echo $banner->getTargetValue() ?>">
            <?php endif; ?>
                <img alt="<?php echo (($banner->getImageAlt()) ? $banner->getImageAlt() :  $banner->getName()); ?>" title="<?php echo (($banner->getImageAlt()) ? $banner->getImageAlt() :  $banner->getName()); ?>"  src="<?php echo $block->getBannerImageUrl($banner) ?>" class="img-responsive"/>
            <?php if($banner->getClickUrl()): ?>
            </a>
            <?php endif; ?>
                        
            <?php if($banner->getShowTitle() && $banner->getName()): ?>
            <h2><?php echo $banner->getName() ?></h2>
            <?php endif; ?>
            
            <?php if($banner->getCaption()): ?>
            <p><?php echo strip_tags($banner->getCaption()) ?></p>
            <?php endif; ?>
            
        </div>
    <?php endforeach ?>
</div>
